#include "p16f877a.inc"
#include "lcd.inc"
#include "input.inc"
#include "display.inc"
#include "tela_app.inc"
#include "tela_game.inc"
    
 __CONFIG _FOSC_EXTRC & _WDTE_OFF & _PWRTE_OFF & _BOREN_OFF & _LVP_OFF & _CPD_OFF & _WRT_OFF & _CP_OFF

GPR_VAR	UDATA								        ; INICIA AS VARIÁVEIS
 ENTRADA	    RES	1
 PONTUACAO_U	    RES	1
 PONTUACAO_D	    RES	1
 JOGO_RODANDO	    RES 1
 TIMER_COUNT	    RES 1
 TIMER_MOVE_PEDRA   RES	1	    
 LIB_VARS
 LCD_VARS
 DISPLAY_VARS
 TELA_GAME_VARS


RES_VECT  CODE    0x0000            
    GOTO    START                   

ISR CODE 0X0004    
 BTFSC INTCON, TMR0IF	;INTERRUPÇÃO DE TEMPO
 CALL TIMER_INT
 RETFIE
 
TIMER_INT:
   BCF INTCON, TMR0IF
   MOVLW D'126'
   MOVF TMR0
  
   CMPFL JOGO_RODANDO,1
   JNE SKIP_INC_TEMPO_VOANDO
   
   INCF TIMER_MOVE_PEDRA
   CMPFL TIMER_MOVE_PEDRA,15
   JNE SKIP_MOVE_PEDRA
   MOVLF 0,TIMER_MOVE_PEDRA
   
   BTFSC CENA_LINHA_4,7
   GOTO RESTART_MOVE
   
   RLF CENA_LINHA_4,1
   RLF CENA_LINHA_4_1,1
   GOTO SKIP_MOVE_PEDRA
   
RESTART_MOVE:
   CMPFL VOANDO,1
   JE RESTART_MOVE_CONT
   MOVLF 0,JOGO_RODANDO
RESTART_MOVE_CONT:   
   MOVLF D'1',CENA_LINHA_4_1
   MOVLF D'1',CENA_LINHA_4
   RLF CENA_LINHA_4,1
   RLF CENA_LINHA_4_1,1
   
SKIP_MOVE_PEDRA:
    
   CMPFL VOANDO,0
   JE SKIP_INC_TEMPO_VOANDO
   INCF TEMPO_VOANDO
   
   CMPFL TEMPO_VOANDO, 22
   JNE SKIP_INC_TEMPO_VOANDO 
   MOVLF 0,VOANDO
   MOVLF 0,TEMPO_VOANDO
   
SKIP_INC_TEMPO_VOANDO:   
 
   DECFSZ TIMER_COUNT
   RETURN
   
   MOVLW D'60'
   MOVWF TIMER_COUNT
   
   CMPFL JOGO_RODANDO,1
   JNE EXIT_TIMER
   
   CMPFL PONTUACAO_U,9
   JNE SK_INC_PT_D
   MOVLF 0,PONTUACAO_U
   INCF PONTUACAO_D
   GOTO EXIT_TIMER
   
SK_INC_PT_D:
   INCF PONTUACAO_U								; AUMENTA 1 PONTO POR SEGUNDO

EXIT_TIMER:
   RETURN

MAIN_PROG CODE                      
 
DEFINE_FUNCS:									; DECLARA AS FUNÇÕES DAS BIBLIOTECAS
 DEFINE_LCD_FUNCS								
 DEFINE_INPUT_FUNCS ENTRADA
 TELAS_DEF
 DEFINE_DISPLAY_FUNCS
 TELA_GAME_DEFINE_FUNCS
 
SETUP_TIMER_INT:								; CONFIGURA CONTADOR
 BANK1
 BCF TRISB, RB1
 BCF OPTION_REG, PSA								; HABILITA PSA PRO TIMER 0
 BSF OPTION_REG, PS2
 BSF OPTION_REG, PS1
 BCF OPTION_REG, PS0
 BANK0
 BCF TRISB, RB1
										
										
 MOVLW D'126'
 MOVWF TMR0
 
 MOVLW D'60'
 MOVWF TIMER_COUNT
 
 BCF INTCON, TMR0IF
 BSF INTCON, TMR0IE
 BSF INTCON, GIE
 RETURN 
 
TELA_INICIAL:															   
 CALL LCD_INIT									; INICIA O LCD
 CALL TELA_AP									; MOSTRA A TELA INICIAL DO JOGO
 DELAY_S D'1'
 DELAY_S D'1'
 DELAY_S D'1'
 DELAY_S D'1'
 DELAY_S D'1'
 RETURN
 
								 
START:
 MOVLF D'1',CENA_LINHA_4
 CALL TELA_INICIAL
 CALL SETUP_TIMER_INT
 
LOOP:
 CMPFL JOGO_RODANDO,1								; SE O JOGO NÃO ESTIVER RODANDO VAI PARA O MENU, CASO CONTRARIO VAI PRO JOGO
 JE GAME
 MOVLF 0,PONTUACAO_U
 MOVLF 0,PONTUACAO_D
 MOVLF 0,CENA_LINHA_4
 MOVLF 0,CENA_LINHA_4_1
 
MENU:
 CALL TELA_INSTRUCOES								; MOSTRA A TELA COM INSTRUÇÕES
 CALL ENABLE_KEYBOARD								; ATIVA O TECLADO
MENU_INP:
 CALL CORNIO_INPUT								; PEGA A ENTRADA DO USUÁRIO, SE NADA FOI PRESSIONADO VOLTA PARA MENU
 CMPFL ENTRADA,KEY_NONE
 JE MENU_INP
 MOVLF 1,JOGO_RODANDO
 DELAY_MS D'250'
 CALL LCD_ENABLE
 LCD_CMD L_CLR
 
GAME:
 CALL ENABLE_KEYBOARD
 CALL CORNIO_INPUT
 CMPFL ENTRADA,KEY_NONE
 JE PLAYER_NOT_JUNP
 MOVLF 1,VOANDO
 
PLAYER_NOT_JUNP:
 CALL TELA_GAME

 GOTO LOOP
 END